# Generated by Django 4.2.6 on 2023-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('telegram', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('grade', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=10)),
                ('faculty', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=25)),
                ('job_date_of_start', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
