# Generated by Django 4.2.6 on 2023-11-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFallSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
