# Generated by Django 4.2.6 on 2023-11-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFallSchool', '0009_alter_user_avatar_alter_user_course_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
